{
 "title": "OpenTelemetry .Net",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_ds", "query": "prometheus" },
   {
    "name": "exported_job",
    "label": "Service Name",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count,exported_job)"
    }
   },
   {
    "name": "service_environment",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count{exported_job=\"$exported_job\"},service_environment)"
    }
   },
   {
    "name": "service_version",
    "label": "Service version",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count{exported_job=\"$exported_job\", service_environment=\"$service_environment\"},service_version)"
    }
   },
   {
    "name": "service_instance_id",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{exported_job=\"$exported_job\", service_environment=\"$service_environment\", service_version=\"$service_version\"},service_instance_id)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{exported_job=\"$exported_job\", service_environment=\"$service_environment\", service_version=\"$service_version\", service_instance_id=~\"$service_instance_id\"},http_route)"
    }
   },
   {
    "name": "http_response_status_code",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{exported_job=\"$exported_job\", service_environment=\"$service_environment\", service_version=\"$service_version\", service_instance_id=~\"$service_instance_id\", http_route=~\"$http_route\"},http_response_status_code)"
    }
   },
   { "name": "top", "label": "Top", "query": "1, 5, 10" },
   { "name": "percentile", "query": "p95 : 0.95, p50 : 0.50" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\", service_version=\"${service_version}\", service_environment=\"${service_environment}\", service_instance_id=~\"${service_instance_id}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval])))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "heatmap",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-httpserverrequestduration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{exported_job=\"${exported_job}\", service_version=\"${service_version}\", service_environment=\"${service_environment}\", service_instance_id=~\"${service_instance_id}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Http Server requests Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (service_instance_id,http_request_method,http_route,url_scheme,http_response_status_code) (rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\", service_version=\"${service_version}\", service_environment=\"${service_environment}\", service_instance_id=~\"${service_instance_id}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{service_instance_id}}/{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Http Server requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by(service_instance_id, url_scheme, http_request_method, http_route, http_response_status_code, error_type) (rate(http_server_request_duration_seconds_count{exported_job=\"${exported_job}\", service_version=\"${service_version}\", service_environment=\"${service_environment}\", service_instance_id=~\"${service_instance_id}\", http_route=~\"${http_route}\", http_response_status_code!~\"[1-3]..\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{service_instance_id}}/{{http_route}}: {{http_response_status_code}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Http Server requests Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(http_server_request_duration_seconds_bucket{exported_job=\"$exported_job\", service_environment=\"$service_environment\", service_instance_id=~\"${service_instance_id}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval])) by (le, http_request_method, url_scheme, service_instance_id, http_route, http_response_status_code)\r\n    )\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{service_instance_id}}/{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "In-flight HTTP requests",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-httpserveractive_requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_instance_id, http_request_method, url_scheme) (rate(http_server_active_requests{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Routing match attempts",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-aspnetcoreroutingmatch_attempts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_instance_id,http_route,aspnetcore_routing_is_fallback) (rate(aspnetcore_routing_match_attempts_total{exported_job=\"$exported_job\", service_environment=\"$service_environment\", aspnetcore_routing_match_status!=\"success\" }[$__rate_interval]))",
     "legendFormat": "{{service_instance_id}}{{http_route}} failure (fallback:{{aspnetcore_routing_is_fallback}})"
    },
    {
     "expr": "sum by (service_instance_id,http_route) (rate(aspnetcore_routing_match_attempts{exported_job=\"$exported_job\", service_environment=\"$service_environment\", aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"true\" }[$__rate_interval]))",
     "legendFormat": "{{service_instance_id}}{{http_route}} fallback route"
    },
    {
     "expr": "sum by (service_instance_id,http_route) (rate(aspnetcore_routing_match_attempts{exported_job=\"$exported_job\", service_environment=\"$service_environment\", aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"false\" }[$__rate_interval]))",
     "legendFormat": "{{service_instance_id}}{{http_route}} success"
    }
   ]
  },
  {
   "title": "Active connections (kestrel)",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-kestrelactive_connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (network_type, network_transport, server_address, server_port) (max_over_time(kestrel_active_connections{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__interval]))",
     "legendFormat": "{{network_type}} {{network_transport}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  {
   "title": "Queued connections (kestrel)",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-kestrelqueued_connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (network_type, network_transport, server_address, server_port) (max_over_time(kestrel_queued_connections{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__interval]))",
     "legendFormat": "{{network_type}} {{network_transport}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  {
   "title": "Connections Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(kestrel_connection_duration_seconds_bucket{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval])) by (le,network_protocol_name,network_protocol_version,network_transport,network_type,server_address,server_port)\r\n    )\r\n)",
     "legendFormat": "{{network_type}} {{network_transport}}/{{network_protocol_name}}{{network_protocol_version}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  { "title": "Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Games request total by name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "games_request_count_total{service_name=\"GameClientApi\"}",
     "legendFormat": "{{request_method}}::{{request_path}}"
    }
   ]
  },
  {
   "title": "Games request total by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum by (request_method, request_path) (games_request_count_total{service_name=\"GameClientApi\"})",
     "legendFormat": "{{request_method}}::{{request_path}}{{username}}"
    }
   ]
  },
  {
   "title": "Games request sum by name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (username) (games_request_count_total{service_name=\"GameClientApi\"})",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Games request rate by request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by (request_method,request_path) (rate(games_request_count_total{service_name=\"GameClientApi\"}[5m]))",
     "legendFormat": "{{request_method}}::{{request_path}}"
    }
   ]
  },
  {
   "title": "Games request rate by name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(games_request_count_total{service_name=\"GameClientApi\"}[5m])",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Games request rate by request/name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum by (request_method,request_path, username) (rate(games_request_count_total{service_name=\"GameClientApi\"}[5m]))",
     "legendFormat": "{{request_method}}::{{request_path}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (state) (rate(process_cpu_time_seconds_total{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(process_memory_usage_bytes{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(process_thread_count{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "Process Threads"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "GC Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(process_runtime_dotnet_gc_objects_size_bytes{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "GC Objects size"
    }
   ]
  },
  {
   "title": "GC Allocations size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_gc_allocations_size_bytes_total{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "GC Allocation Size"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (generation) (rate(process_runtime_dotnet_gc_collections_count_total{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_exceptions_count_total{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Thread Pool Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(process_runtime_dotnet_thread_pool_threads_count{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "Thead Pool Threads"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(process_runtime_dotnet_thread_pool_queue_length{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval]))",
     "legendFormat": "Thread Pool Queue Length"
    }
   ]
  },
  { "title": "HTTP Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (http_connection_state, server_address, server_port, url_scheme, network_protocol_version) (max_over_time(http_client_open_connections{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__interval]))",
     "legendFormat": "{{http_connection_state}} {{server_address}}:{{server_port}} {{url_scheme}}{{network_protocol_version}}"
    }
   ]
  },
  {
   "title": "Http Client requests Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(http_client_request_duration_seconds_bucket{exported_job=\"$exported_job\", service_environment=\"$service_environment\"}[$__rate_interval])) by (le, http_request_method, url_scheme, http_route, http_response_status_code,server_address,server_port,network_protocol_version)\r\n    )\r\n)",
     "legendFormat": "{{url_scheme}}/{{network_protocol_version}} {{server_address}}:{{server_port}} {{http_request_method}}: {{http_response_status_code}}"
    }
   ]
  }
 ]
}